id: IFD484444
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T15:31:46+00:00'
last_modified: '2022-06-08T16:26:57.779314+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN506
  title: གྲྭ་ཏོག་གསེར་གསུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    96A5:
      image_group_id: I3CN4548
      title: Volume 1 of grwa tog gser gsum/
      total_pages: 940
      order: 1
      base_file: 96A5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
