id: P007060
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN506
  title: གྲྭ་ཏོག་གསེར་གསུམ།
  author: ''
  volumes:
    25d512120fed4e01b771814b994930db:
      image_group_id: I3CN4548
      title: Volume 1 of grwa tog gser gsum/
      volume_number: 1
      total_pages: 940
      base_file: v001.txt
