id: P007060
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN506
  title: གྲྭ་ཏོག་གསེར་གསུམ།
  author: ''
  volumes:
    48eeb98a420d4f6c9ed05c7a9331bafe:
      image_group_id: I3CN4548
      title: ''
      volume_number: 1
      total_pages: 940
ebook_metadata:
  title: གྲྭ་ཏོག་གསེར་གསུམ།
  author: ''
  sku: P007060
  cover: cover.jpg
  layers:
  - pagination
